// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017.commands;

import org.usfirst.frc253.Code2017.Robot;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class AutoGearBackUp extends Command {
	
	private Ultrasonic ultraLeft;
	private Ultrasonic ultraRight;
	
    public AutoGearBackUp() {
    	requires(Robot.drivetraintank);
    	requires(Robot.sensorData);
    	ultraLeft = Robot.sensorData.ultraLeft;
    	ultraRight = Robot.sensorData.ultraRight;
    	ultraLeft.setAutomaticMode(true);
		ultraRight.setAutomaticMode(true);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setTimeout(1.0);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double rangeLeft = ultraLeft.getRangeInches();
    	double rangeRight = ultraRight.getRangeInches();
    	SmartDashboard.putNumber("Left Ultrasonic", rangeLeft);
    	SmartDashboard.putNumber("Right Ultrasonic", rangeRight);
    	
    	if(((rangeLeft + rangeRight)/2.00) > 13.00){
    		end();
    	} else {
    		//left
    		Robot.drivetraintank.setLeft_Back(.25);
        	Robot.drivetraintank.setLeft(.25);
        	//right
        	Robot.drivetraintank.setRight_Back(.25);
        	Robot.drivetraintank.setRight(.25);
        	//update distances
        	rangeLeft = ultraLeft.getRangeInches();
        	rangeRight = ultraRight.getRangeInches();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetraintank.setLeft_Back(0);
    	Robot.drivetraintank.setLeft(0);
    	Robot.drivetraintank.setRight(0);
    	Robot.drivetraintank.setRight_Back(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
