// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc253.Code2017.Robot;

public class DeployGear extends Command {

    public DeployGear() {
    	
    	//Subsystem requirements
        requires(Robot.gearFlip);
    }

    protected void initialize() {
    }

    protected void execute() {
    	//Deploy gear
    	Robot.gearFlip.DeployGear();
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    	//Stops gear flip
    	Robot.gearFlip.FullStop();
    }

    protected void interrupted() {
    	//Stops gear flip
    	Robot.gearFlip.FullStop();
    }
}
