// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc253.Code2017.Robot;

/**
 *
 */
public class ManualAuto extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public ManualAuto() {
    	requires(Robot.drivetraintank);
    	requires(Robot.gearFlip);
    	requires(Robot.sensorData);

        addSequential(new ManualAutoStraightDrive());
        addSequential(new AutoGearBackUp());
        addSequential(new AutoGearDeploy());
        addSequential(new AutoRetract());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
