// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.Ultrasonic;

public class RobotMap {
	
	//Drive train ports
    public static final int driveMotorLeft = 2; // 2
	public static final int driveMotorLeft_Back = 3; //3
	public static final int driveMotorRight = 0; //0
	public static final int driveMotorRight_Back = 1; //1
	
	//Motor declarations
	public static Spark gearFlipSpark1;
	public static Servo servoServo1;
	public static Spark climberSpark1;
	
	//Sensor declarations
    public static Ultrasonic sensorDataUltrasonic1;
    public static Ultrasonic sensorDataUltrasonic2;
    public static AnalogGyro sensorDataGyroscope1;
    public static DigitalInput sensorDataPhoto1;
    //These are referenced in init()

    //Drive train directions
	public static final int driveMotorLeftDir = -1; //-1
	public static final int driveMotorRightDir = 1; //1
	public static final int driveMotorRightBackDir = 1; //1
	public static final int driveMotorLeftBackDir = -1; //-1
	
	//Drive tran slower speed
	public static final double CREEP_SPEED = 0.5;
	public static final double CREEP_SPEED_ULTRA = .125;

    public static void init() {
    	
    	//Gear flipper spark port
        gearFlipSpark1 = new Spark(4);
        LiveWindow.addActuator("GearFlip", "Spark 1", (Spark) gearFlipSpark1);
        
        //Camera servo port
        servoServo1 = new Servo(5);
        LiveWindow.addActuator("Servo", "Servo 1", (Servo) servoServo1);
        
        climberSpark1 = new Spark(6);
        LiveWindow.addActuator("Climber", "Spark 1", (Spark) climberSpark1);
        
        //Ultrasonic sensor ports
        sensorDataUltrasonic1 = new Ultrasonic(0,1);
        LiveWindow.addSensor("SensorData", "Ultrasonic 1", sensorDataUltrasonic1);
        
        sensorDataUltrasonic2 = new Ultrasonic(5,6);
        LiveWindow.addSensor("SensorData", "Ultrasonic 2", sensorDataUltrasonic2);
        
        //Gyroscope port
        sensorDataGyroscope1 = new AnalogGyro(0);
        LiveWindow.addSensor("SensorData", "Gyroscope 1", sensorDataGyroscope1);
        
        //Photoelectric sensor port
        sensorDataPhoto1 = new DigitalInput(4);
        LiveWindow.addSensor("SensorData", "Photoelectric 1", sensorDataPhoto1);
    }
}
