// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017.subsystems;

import org.usfirst.frc253.Code2017.RobotMap;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Climber extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Spark spark1 = RobotMap.climberSpark1;

    public void initDefaultCommand() {}

    	public Climber() {
        	super();
        	 ClimbUp();
        	 ClimbDown();
        	 ClimbUpSlow();
        	 ClimbDownSlow();
        	 ClimbUpSlower();
        	 ClimbDownSlower();
        	 ClimbUpEvenSlower();
        	 ClimbDownEvenSlower();
        	 ClimbUpSlowest();
        	 ClimbDownSlowest();
        	 FullStop();
    	}
    	public void ClimbUp(){
    		spark1.set(1);
    	}
    	public void ClimbDown(){
    		spark1.set(-1);
    	}
    	public void ClimbUpSlow(){
    		spark1.set(.8);
    	}
    	public void ClimbDownSlow(){
    		spark1.set(-.8);
    	}
    	public void ClimbUpSlower(){
    		spark1.set(.6);
    	}
    	public void ClimbDownSlower(){
    		spark1.set(-.6);
    	}
    	public void ClimbUpEvenSlower(){
    		spark1.set(.4);
    	}
    	public void ClimbDownEvenSlower(){
    		spark1.set(-.4);
    	}
    	public void ClimbUpSlowest(){
    		spark1.set(.2);
    	}
    	public void ClimbDownSlowest(){
    		spark1.set(-.2);
    	}
    	public void FullStop(){
    		spark1.set(0.00);
    	}
}



