// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2017.subsystems;

import org.usfirst.frc253.Code2017.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Servo extends Subsystem {
	
	//Declares actuator, connects to RobotMap
    public final edu.wpi.first.wpilibj.Servo servo1 = RobotMap.servoServo1;

    public void initDefaultCommand() {}
    
    public Servo(){
    	super();
    	SpinForward();
    	SpinBack();
    }
    public void SpinForward(){
    	//Sets servo to forward position
    	servo1.set(.5);
    	servo1.setAngle(0);
    }
    public void SpinBack(){
    	//Sets servo to backward position
    	servo1.set(.5);
    	servo1.setAngle(180);
    }
}
//
